add endpoint to verify verifiable presentation
catenax-ng/product-core-managed-identity-wallets pull request #17
Opened 2022-07-13 09:13 UTC by MajdT51

2022-07-13 11:39 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/routes/VpRoutes.kt
> +            notarizedAuthenticate(AuthConstants.JWT_AUTH_UPDATE) {
Shall we require the "UPDATE" role for the validation? There is actually no update happening, right? I would be OK with having "VIEW" role.

2022-07-13 11:44 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/routes/VpRoutes.kt
> +                        securitySchemes = setOf(AuthConstants.JWT_AUTH_UPDATE.name)
Same here, see my comment above

2022-07-13 11:45 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +                throw UnprocessableEntityException("VC with id ${vc.id} is not valid due its issuanceDate")
I would suggest to write "VC" as "Verifiable credential"

2022-07-13 11:46 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +                throw UnprocessableEntityException("VC with id ${vc.id} is not valid due its expirationDate")
Same here, I would suggest to write "VC" as "Verifiable credential"

2022-07-13 11:46 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +            throw UnprocessableEntityException("Cannot verify VC due to missing proof")
Same here, I would suggest to write "VC" as "Verifiable credential"

2022-07-13 11:47 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +            throw UnprocessableEntityException("AcaPy VC ${vc.id} validation failed: ${e.message}")
I would word it like "External validation failed of the verifiable credential ${vc.id} failed: ${e.message}" and leave out AcaPy

2022-07-13 11:47 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +            throw UnprocessableEntityException("VC with id ${vc.id} is not valid.$message")
Same here, I would suggest to write "VC" as "Verifiable credential"

2022-07-13 11:47 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +            throw UnprocessableEntityException("Cannot verify VP due to missing holder DID")
Same here, I would suggest to write "VP" as "Verifiable presentation"

2022-07-13 11:47 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +            throw UnprocessableEntityException("Cannot verify VP due to missing proof")
Same here, I would suggest to write "VP" as "Verifiable presentation"

2022-07-13 11:49 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +            throw UnprocessableEntityException("AcaPy VP validation failed ${e.message}")
I would suggest to write it like "External verifiable presentation validation failed: ${e.message}"

2022-07-13 11:49 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +            throw UnprocessableEntityException("VP is not valid.$message")
Same here, I would suggest to write "VP" as "Verifiable presentation"

2022-07-13 11:55 UTC, MajdT51 commented on src/main/kotlin/net/catenax/core/managedidentitywallets/routes/VpRoutes.kt
> +            notarizedAuthenticate(AuthConstants.JWT_AUTH_UPDATE) {
I used update because it is not a GET method. but yes View is better because we are not changing anything.

2022-07-13 15:47 UTC, matthiashub-porsche commented
Thanks for adding the test, LGTM

2022-07-13 20:00 UTC, jpbu requested changes
I only reviewed it in GitHub and did not test it locally, looks good, thanks, but a few remaining comments.

2022-07-14 07:30 UTC, MajdT51 commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/AcaPyWalletServiceImpl.kt
> +            throw UnprocessableEntityException("Cannot verify verifiable presentation due to missing holder DID")
It will be extracted from the verification method

2022-07-14 10:23 UTC, jpbu approved these changes

2022-07-14 20:25 UTC, merged