pull data from PBDM daily
catenax-ng/product-core-managed-identity-wallets pull request #21
Opened 2022-07-21 14:32 UTC by MajdT51

2022-07-21 18:03 UTC, matthiashub-porsche requested changes

2022-07-21 18:03 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/routes/BusinessPartnerDataRoutes.kt
> +                PostInfo<Unit, Unit, String>(
Re the whole method: I think we can leave the POST as is, if someone wants to POST us updates it is also fine

2022-07-21 18:03 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/BusinessPartnerDataService.kt
> +                            println("HTTP status: ${response.status.value}")
Where is this `println` going to?

2022-07-21 18:03 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/BusinessPartnerDataService.kt
> +                                             bpmdConfig: BPMDConfig
Variable name should also read `bpdmConfig`

2022-07-21 18:03 UTC, matthiashub-porsche commented on src/main/resources/application.conf
>      url=${CX_DATAPOOL_URL}
Actually datapool url and bpdm url are the same and thus only one should be used

2022-07-21 18:03 UTC, matthiashub-porsche commented on src/test/kotlin/net/catenax/core/custodian/ApplicationTest.kt
>                  addHeader(HttpHeaders.ContentType, ContentType.Application.Json.toString())
As mentioned above, I would leave the existing POST method in as is

2022-07-22 09:47 UTC, jpbu reviewed
Thanks, I reviewed it in GitHub, did not yet test it locally. I second the comments of @matthiashub-porsche except the one where I replied.

2022-07-22 09:47 UTC, jpbu commented on src/main/kotlin/net/catenax/core/managedidentitywallets/routes/BusinessPartnerDataRoutes.kt
> +                PostInfo<Unit, Unit, String>(
I don't fully agree, having both push and pull seems confusing and in a push scenario we also have to establish some kind of trust that we can rely on the data that is posted. That's why I would prefer to restrict it to a pull from a trusted data source.

2022-07-22 09:47 UTC, jpbu commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/BusinessPartnerDataServiceImpl.kt
> +                extractedBPData.add(getBusinessDate(bpn, accessToken))
Should be called `getBusinessPartnerData` instead of `getBusinessDate`

2022-07-22 09:47 UTC, jpbu commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/BusinessPartnerDataServiceImpl.kt
> +            issueAndUpdateCatenaXCredentials(it)
Why do we need an additional forEach loop here instead of directly calling this in the `listOfBpns.forEach`?

2022-07-22 09:47 UTC, jpbu commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/BusinessPartnerDataServiceImpl.kt
> +        return walletService.getAllBpns()
I think this function does not provide any benefit and we could call the wallet service directly instead

2022-07-22 09:47 UTC, jpbu commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/BusinessPartnerDataServiceImpl.kt
> +        val requestUrl = "${bpdmConfig.url}/api/catena/business-partner/$bpn?idType=BPN"
I think we should add a comment and disclaimer somewhere here that this is just a temporary solution and will not scale for many wallets since we are doing one request per BPN

2022-07-22 09:47 UTC, jpbu commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/WalletService.kt
> +    suspend fun deleteCredential(id: String): Boolean
Where is this function actually needed/called?

2022-07-22 11:15 UTC, matthiashub-porsche commented on src/main/kotlin/net/catenax/core/managedidentitywallets/routes/BusinessPartnerDataRoutes.kt
> +                PostInfo<Unit, Unit, String>(
Ah valid point! For me the authorisation was "good enough" to be a "trusted data source". I concur, with one suggestion: calling it rather "refreshBusinessPartnerData" as it is to me a manual refresh from a trusted data source - which actually should happen later automatically via the message broker handling.

2022-07-25 07:14 UTC, MajdT51 commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/BusinessPartnerDataServiceImpl.kt
> +            issueAndUpdateCatenaXCredentials(it)
issueAndUpdateCatenaXCredentials is slow and depending on the number of BPDs I think the BPMD token will expire. Should i check the token each time if it expired and then move this line to the first forEach loop?

2022-07-25 07:27 UTC, MajdT51 commented on src/main/kotlin/net/catenax/core/managedidentitywallets/routes/BusinessPartnerDataRoutes.kt
> +                PostInfo<Unit, Unit, String>(
okay, I will change the path to refreshBusinessPartnerData . But should I change it to Patch or Put?

2022-07-25 07:28 UTC, MajdT51 commented on src/main/kotlin/net/catenax/core/managedidentitywallets/services/BusinessPartnerDataService.kt
> +                            println("HTTP status: ${response.status.value}")
currently for debugging and the status and description will be shown in the console

2022-07-25 07:44 UTC, MajdT51 commented on src/main/kotlin/net/catenax/core/managedidentitywallets/plugins/Scheduler.kt
> +        recurringJob("bpdm-update", Cron.daily()) {
yes "0 0 * * *";

2022-07-25 10:17 UTC, closed without merging