imporve implementation and doc of roles
catenax-ng/product-core-managed-identity-wallets pull request #23
Opened 2022-07-28 10:10 UTC by MajdT51

2022-07-28 12:16 UTC, matthiashub-porsche requested changes

2022-07-28 13:17 UTC, jpbu reviewed
Reviewed it in GitHub, looks good, a few comments.

2022-07-28 13:29 UTC, matthiashub-porsche commented on src/main/kotlin/org/eclipse/tractusx/managedidentitywallets/routes/AuthorizationHandler.kt
> +        if (principal.role == role) {
To my understanding this function is called with a single role only (done by the _notarized_ thing around)

2022-07-28 13:47 UTC, jpbu commented on src/main/kotlin/org/eclipse/tractusx/managedidentitywallets/routes/AuthorizationHandler.kt
> +        if (principal.role == role) {
We should validate that with the local Keycloak setup if not yet done. In the ApplicationTest it looks like only JWTs with a single role are created, does that correctly reflect how they are used in the Keycloak scenario?

2022-07-28 13:48 UTC, matthiashub-porsche commented on src/main/kotlin/org/eclipse/tractusx/managedidentitywallets/routes/AuthorizationHandler.kt
> +        if (principal.role == role) {
Yes, great suggestion to put it in the test case, full ack - I only tested with Postman my earlier implementation

2022-07-28 13:50 UTC, matthiashub-porsche commented on src/main/kotlin/org/eclipse/tractusx/managedidentitywallets/routes/AuthorizationHandler.kt
> +        if (principal.role == role) {
Here the keycloak example:

```
  "resource_access": {
    "Cl5-CX-Custodian": {
      "roles": [
        "delete_wallets",
        "update_wallets",
        "view_wallets",
        "add_wallets"
      ]
    }
  },
```

2022-07-29 17:53 UTC, matthiashub-porsche commented on src/test/kotlin/org/eclipse/tractusx/managedidentitywallets/ApplicationTest.kt
> +                handleRequest(HttpMethod.Get, "/api/wallets") {
Is the return code of `403` returned in the HTTP call? Could we also add an additional test for that?

2022-07-29 17:56 UTC, matthiashub-porsche commented
> Do we still need the roleMap and roleMappings? It looks like it is now only used in a test

@jpbu Quick follow-up question: where do you see that? For me the configuration check on startup is quite valuable:

```
        if (roleMap[AuthorizationHandler.ROLE_CREATE_WALLETS] == null) {
             log.error("Configuration error, ${AuthorizationHandler.ROLE_CREATE_WALLETS} role mapping not defined, system will not behave correctly!")
             throw Exception("Configuration error, ${AuthorizationHandler.ROLE_CREATE_WALLETS} role mapping not defined, system will not behave correctly!")
         }
```

2022-07-29 18:59 UTC, jpbu commented
> > Do we still need the roleMap and roleMappings? It looks like it is now only used in a test
> 
> @jpbu Quick follow-up question: where do you see that? For me the configuration check on startup is quite valuable:
> 
> ```
>         if (roleMap[AuthorizationHandler.ROLE_CREATE_WALLETS] == null) {
>              log.error("Configuration error, ${AuthorizationHandler.ROLE_CREATE_WALLETS} role mapping not defined, system will not behave correctly!")
>              throw Exception("Configuration error, ${AuthorizationHandler.ROLE_CREATE_WALLETS} role mapping not defined, system will not behave correctly!")
>          }
> ```

@matthiashub-porsche I don't see the `roleMap` used anywhere, same as the `roleMappings` property. In my understanding it was only necessary for mapping the jwtConfigs to the roles, this has now been removed and the roles are checked in the `AuthorizationHandler`.  I quickly tried to remove the `roleMap` from the code, all compiles successfully and besides the `testMissingRoleMapping` test case that explicitly (and only) tests this role mapping all the other test cases run successfully.

2022-07-29 20:39 UTC, matthiashub-porsche commented
> > > Do we still need the roleMap and roleMappings? It looks like it is now only used in a test
> > 
> > 
> > @jpbu Quick follow-up question: where do you see that? For me the configuration check on startup is quite valuable:
> > ```
> >         if (roleMap[AuthorizationHandler.ROLE_CREATE_WALLETS] == null) {
> >              log.error("Configuration error, ${AuthorizationHandler.ROLE_CREATE_WALLETS} role mapping not defined, system will not behave correctly!")
> >              throw Exception("Configuration error, ${AuthorizationHandler.ROLE_CREATE_WALLETS} role mapping not defined, system will not behave correctly!")
> >          }
> > ```
> 
> @matthiashub-porsche I don't see the `roleMap` used anywhere, same as the `roleMappings` property. In my understanding it was only necessary for mapping the jwtConfigs to the roles, this has now been removed and the roles are checked in the `AuthorizationHandler`. I quickly tried to remove the `roleMap` from the code, all compiles successfully and besides the `testMissingRoleMapping` test case that explicitly (and only) tests this role mapping all the other test cases run successfully.

@jpbu then it is a wrong logic =) because the roles are not named necessarily the same as we name it internally, e.g. the portal named it `add_wallets` instead of `create_wallets`, thus I added the map lookup. I've pushed a small update, maybe @MajdT51 can review and test on his end.

2022-08-02 10:18 UTC, MajdT51 commented on src/main/kotlin/org/eclipse/tractusx/managedidentitywallets/models/BusinessPartnerDataDto.kt
> +data class BusinessPartnerDataDtoParameter(
done

2022-08-02 10:18 UTC, MajdT51 commented on src/main/kotlin/org/eclipse/tractusx/managedidentitywallets/models/BusinessPartnerDataDto.kt
> +    @Field(description = "The DID or BPN of the Wallet to update", name = "identifier")
done

2022-08-02 10:19 UTC, MajdT51 commented on src/main/kotlin/org/eclipse/tractusx/managedidentitywallets/routes/AuthorizationHandler.kt
> +        if (principal.role == role) {
done

2022-08-02 10:19 UTC, MajdT51 commented on src/main/kotlin/org/eclipse/tractusx/managedidentitywallets/routes/AuthorizationHandler.kt
> +            log.error(errorMsg)
outdated

2022-08-02 10:21 UTC, MajdT51 commented on src/test/kotlin/org/eclipse/tractusx/managedidentitywallets/ApplicationTest.kt
> +                handleRequest(HttpMethod.Get, "/api/wallets") {
done. added mapping error -> http code to the testcases

2022-08-02 13:55 UTC, jpbu approved these changes
Double-checked and tested locally with the latest version, looks good to me now.

2022-08-03 06:17 UTC, merged