use jacoco for coverage, add more tests
catenax-ng/product-core-managed-identity-wallets pull request #27
Opened 2022-08-08 13:21 UTC by MajdT51

2022-08-08 15:57 UTC, jpbu requested changes
Thanks, I reviewed it and tested locally, overall looks good. A few comments directly inline.

2022-08-08 15:57 UTC, jpbu commented on build.gradle.kts
> +    classDirectories.setFrom(
Can we somehow re-use this from the jacocoTestReport instead of copying everything?

2022-08-08 15:57 UTC, jpbu commented on build.gradle.kts
> +                    "**/services/BusinessPartnerDateServiceImpl*" // mocked
The correct name of the class is BusinessPartnerDataServiceImpl (Data instead of Date) - is this exclusion really working?

Also, I wonder a bit why interfaces need to be excluded explicitly, is that a Kotlin related thing?

We should also document the exclusions in the README to provide guidance and reasoning on what should/can be excluded for future changes.

2022-08-08 15:57 UTC, jpbu commented on src/test/kotlin/org/eclipse/tractusx/managedidentitywallets/ApplicationTest.kt
> +
Now that it has become quite large, I would suggest to split the tests into multiple test classes, e.g. related to the routes or service classes.

2022-08-08 15:57 UTC, jpbu commented on README.md
> +* To generate the report run the command `./gradle jacocoTestReport`
We should be consistent and always use gradlew in the README commands

2022-08-09 14:06 UTC, MajdT51 commented on build.gradle.kts
> +                    "**/services/BusinessPartnerDateServiceImpl*" // mocked
"is this exclusion really working?" Yes because the Impl was excluded mistakenly at line 100

interfaces need to be excluded explicitly -> they shouldn't but we are using a create function in a companion object in the interface. example:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/50261972/183670004-407cc1e9-86d8-47da-8fbb-928d0a2d2ef1.png">

2022-08-09 14:41 UTC, jpbu commented on build.gradle.kts
> +    classDirectories.setFrom(
Is it possible to load the list of exclusions from a separate file? I think it would be better to not have to adjust the basic build.gradle file every time an exclusion rule changes.

If reuse or loading from a file is not possible, I would suggest to not split this into two tasks but only have one and always do the verification.

2022-08-09 16:32 UTC, jpbu commented on README.md
> +* The excluded Files are
We should not copy the list of currently excluded files yet another time to the README and add some words to it, my previous comment was about explaining the exclusion in general, e.g. why models, entities or interfaces are excluded and what needs to be considered regarding exclusion for future features that will add new files.

2022-08-10 09:26 UTC, jpbu approved these changes

2022-08-10 09:26 UTC, merged